### ISSUE TITLE
Support for resnet as backbone

### ISSUE THREAD

**Issue by a7b23** [HobbitLong/CMC#1]
Hi, thanks for open-sourcing the code. I wanted to know as to when will you enable the support for resnet to be used as a backbone.

**Comment by HobbitLong** [comment]
Hi, Thanks for your interest.

I already uploaded the ResNet backbone [here](https://github.com/HobbitLong/CMC/blob/master/models/resnet.py#L293-L319). If you need to use it asap, simply making the model data-parallel and replacing AlexNet with ResNet should work.

I would like to port my DataParallel/DistributedDataParallel code later, but not now due to other stuff. But you are welcomed to send a PR if you do it by yourself.

**Comment by HobbitLong** [comment]
Hi, @a7b23 

The code for ResNets is available now. I am closing this issue and feel free to reopen if you have further questions.
